<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Article extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'cat_id', 'title','pic', 'video','slug', 'body',  'status', 'countViews', 'countComments'];

    public function slugable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];

    }

    public function getRouteKeyName(): string
    {
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return 'slug';
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
