<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    use HasFactory,SoftDeletes;

//    protected $fillable = ['id', 'user_id', 'category', 'sub_category','title', 'pic', 'video', 'slug', 'body', 'countViews', 'countComments'];

    protected $guarded = [];

    public function sluGable(): array
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];

    }

    public function getRouteKeyName(): string
    {
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return 'slug';
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    public function subcategory(): HasMany
    {
        return $this->hasMany(Category::class);
    }
}
